"""changed opportunity_id to job_id

Revision ID: 9ce1d5933e72
Revises: 2f7be77e740a
Create Date: 2024-10-15 10:26:19.115185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce1d5933e72'
down_revision = '2f7be77e740a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_certificates_opportunity_id_jobs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_certificates_job_id_jobs'), 'jobs', ['job_id'], ['id'])
        batch_op.drop_column('opportunity_id')

    with op.batch_alter_table('hourlogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hourlogs_job_applications_id_job_applications', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_hourlogs_job_applications_id_job_applications'), 'job_applications', ['job_applications_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_job_applications_opportunity_id_jobs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_applications_job_id_jobs'), 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('opportunity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_job_applications_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_job_applications_opportunity_id_jobs', 'jobs', ['opportunity_id'], ['id'])
        batch_op.drop_column('job_id')

    with op.batch_alter_table('hourlogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hourlogs_job_applications_id_job_applications'), type_='foreignkey')
        batch_op.create_foreign_key('fk_hourlogs_job_applications_id_job_applications', 'job_applications', ['job_applications_id'], ['id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_certificates_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_certificates_opportunity_id_jobs', 'jobs', ['opportunity_id'], ['id'])
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
