"""added hours_worked field

Revision ID: c2fba5ed5e68
Revises: 6efce251df59
Create Date: 2024-10-17 10:50:36.099166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fba5ed5e68'
down_revision = '6efce251df59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
