"""changed overall_ratings in volunteer to total_ratings

Revision ID: fe6a5f1950d3
Revises: c2fba5ed5e68
Create Date: 2024-10-27 14:10:19.052212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6a5f1950d3'
down_revision = 'c2fba5ed5e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ratings_given', sa.Integer(), nullable=False))
        batch_op.drop_column('overall_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating', sa.FLOAT(), nullable=False))
        batch_op.drop_column('total_ratings_given')

    # ### end Alembic commands ###
